micronaut:
  application:
    name: complete
  server:
    netty:
      max-header-size: 32768
    cors:
      enabled: true

  http:
    client:
      read-timeout: 10s
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"